/**
 * Categories derived from constants/questions.json.
 * Slug format matches scripts/normalize-questions.ts (slugify of name).
 * Used when Convex is not seeded.
 */

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** Unique categories from questions.json: id, slug (for selection), title (English display) */
const RAW_CATEGORIES: { id: string; name: string }[] = [
  { id: 'g1', name: 'ARK: Survival Evolved' },
  { id: 'g3', name: 'Dota' },
  { id: 'g5', name: 'Halo' },
  { id: 'g6', name: 'League of Legends' },
  { id: 'g7', name: 'Minecraft' },
  { id: 'g8', name: 'Overwatch' },
  { id: 'g9', name: 'Red Dead Redemption' },
  { id: 'g10', name: 'Super Mario Bros.' },
  { id: 'g11', name: 'The Legend of Zelda' },
  { id: 'gen1', name: 'Corporations' },
  { id: 'gen2', name: 'Geography' },
  { id: 'gen3', name: 'Science' },
  { id: 'gen4', name: 'UK' },
  { id: 'gen5', name: 'USA' },
  { id: 'gen6', name: 'Countries and Capitals' },
  { id: 'gen7', name: 'Famous Firsts' },
  { id: 'gen8', name: 'Famous Quotes' },
  { id: 'gen9', name: 'General Knowledge' },
  { id: 'gen10', name: 'Guess The Decade' },
  { id: 'gen11', name: 'Guess the Flag' },
  { id: 'gen12', name: 'Guess the Year' },
  { id: 'gen13', name: 'In between:' },
  { id: 'gen14', name: 'Initials' },
  { id: 'gen15', name: 'Invented Where?' },
  { id: 'gen16', name: 'Match the Nickname' },
  { id: 'gen17', name: 'National Icons' },
  { id: 'gen18', name: 'Odd One Out' },
  { id: 'gen19', name: 'Talab-ul Ilm' },
  { id: 'gen20', name: 'Trump Quotes' },
  { id: 'gen21', name: 'What happened next?' },
  { id: 'gen22', name: 'What\'s the connection?' },
  { id: 'gen23', name: 'Which Country' },
  { id: 'gen24', name: 'Who Said This Quote?' },
  { id: 'gen25', name: 'World Laws' },
  { id: 'gen26', name: 'Before They Were Famous' },
  { id: 'h1', name: '19th Century' },
  { id: 'h2', name: '19th Century Europe' },
  { id: 'h3', name: '20th Century' },
  { id: 'h4', name: '21st Century' },
  { id: 'h5', name: 'Ancient Civilisations' },
  { id: 'h7', name: 'Cold War' },
  { id: 'h8', name: 'European History' },
  { id: 'h11', name: 'The Modern Middle East' },
  { id: 'h12', name: 'UK History' },
  { id: 'h13', name: 'US History' },
  { id: 'h14', name: 'WW1' },
  { id: 'h15', name: 'WW2' },
  { id: 'h16', name: 'European Christendom' },
  { id: 'h17', name: 'Ertugrul' },
  { id: 'h18', name: 'Kuruluş: Osman' },
  { id: 'pc1', name: 'Avatar: The Last Airbender' },
  { id: 'pc2', name: 'Breaking Bad' },
  { id: 'pc3', name: 'Dexter' },
  { id: 'pc4', name: 'DC Extended Universe' },
  { id: 'pc5', name: 'Disney' },
  { id: 'pc6', name: 'Dragon Ball' },
  { id: 'pc7', name: 'Friends' },
  { id: 'pc8', name: 'Game of Thrones' },
  { id: 'pc9', name: 'Harry Potter' },
  { id: 'pc10', name: 'How I Met Your Mother' },
  { id: 'pc11', name: 'James Bond' },
  { id: 'pc13', name: 'Marvel' },
  { id: 'pc14', name: 'Naruto' },
  { id: 'pc15', name: 'One Piece' },
  { id: 'pc16', name: 'Pirates of the Caribbean' },
  { id: 'pc17', name: 'Pokemon' },
  { id: 'pc18', name: 'Prison Break' },
  { id: 'pc20', name: 'SpongeBob SquarePants' },
  { id: 'pc23', name: 'Star Wars' },
  { id: 'pc24', name: 'Stranger Things' },
  { id: 'pc25', name: 'The Big Bang Theory' },
  { id: 'pc26', name: 'Fast and Furious' },
  { id: 'pc28', name: 'The Office US' },
  { id: 'pc31', name: 'Attack on Titan' },
  { id: 'pc32', name: 'Peaky Blinders' },
  { id: 'pc33', name: 'Suits' },
  { id: 's2', name: 'Cricket' },
  { id: 's3', name: 'Formula 1' },
  { id: 's5', name: 'NBA' },
  { id: 's7', name: 'Premier League' },
  { id: 's9', name: 'UEFA Champions League' },
  { id: 's10', name: 'UFC' },
  { id: 's11', name: 'Which Player?' },
  { id: 's12', name: 'FIFA World Cup' },
];

export const FALLBACK_CATEGORIES = RAW_CATEGORIES.map((c) => ({
  id: c.id,
  slug: slugify(c.name),
  title: c.name,
  // Illustrations are resolved by getCategoryPictureSource() in categoryPictures.ts
}));
