/**
 * Builds convex/seed/legacyQuestionKeys.ts: the frozen `<slug>:<points>:<index>` ->
 * `q<UserID>` snapshot taken at the question key transition.
 *
 * The snapshot contains only keys that existed before the change, read from both ends of the
 * transition at pinned refs (never a moving branch):
 *   1992d4d convex/seed/questions.json  (8,912 position-keyed rows)
 *   6291744 convex/seed/questions.json  (the `q<UserID>` seed this PR ships)
 *
 * Every pair is verified by prompt and answer identity, so a question that moved, was
 * swapped, or was removed aborts the build instead of being written. The rows the
 * transition deliberately corrected are listed in CONTENT_CORRECTIONS below and are
 * re-checked, so a stale entry fails the build instead of quietly widening what is allowed.
 *
 * Run: bunx tsx scripts/build-legacy-question-keys.ts
 * (re-run only when the transition refs or the corrections list change; the output is
 * committed, and nothing at runtime rebuilds it from current source data)
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  composeLegacyQuestionKeyPairs,
  type LegacyQuestionKeyRow,
} from './lib/legacyQuestionKeys';

/** The seed the key change replaced. */
const HISTORICAL_REF = '1992d4d';
/** The seed the key change produced (PR #2 reviewed head). */
const TRANSITION_REF = '6291744';

/**
 * Rows whose prompt/answer the transition intentionally corrected (lost characters, Excel
 * serial answers, a stray full stop). Reviewed key by key: this is the complete list of
 * accepted text differences, and the build fails if any entry stops differing.
 */
const CONTENT_CORRECTIONS: readonly string[] = [
  'trump-quotes:200:5',
  '19th-century:100:21',
  '19th-century:100:26',
  '19th-century:100:40',
  '19th-century:200:23',
  '19th-century:200:31',
  '19th-century:200:39',
  '19th-century:300:14',
  'ww2:100:9',
  '19th-century-europe:100:26',
  '20th-century:100:9',
  '20th-century:100:12',
  '20th-century:100:23',
  '20th-century:100:31',
  '20th-century:100:32',
  '20th-century:100:40',
  '20th-century:200:5',
  '20th-century:200:10',
  '20th-century:200:17',
  '20th-century:200:27',
  '20th-century:300:10',
  '20th-century:300:12',
  '20th-century:300:14',
  '20th-century:300:21',
  '20th-century:300:24',
  '21st-century:100:3',
  '21st-century:100:10',
  '21st-century:100:20',
  '21st-century:100:21',
  '21st-century:100:34',
  '21st-century:100:43',
  '21st-century:100:47',
  '21st-century:100:48',
  '21st-century:200:8',
  '21st-century:200:12',
  '21st-century:200:19',
  '21st-century:300:14',
  '21st-century:300:15',
  '21st-century:300:17',
  '21st-century:300:18',
  '21st-century:300:21',
  'breaking-bad:200:11',
  'stranger-things:200:27',
  'the-big-bang-theory:100:2',
  'friends:100:3',
  'friends:300:10',
  'friends:300:11',
  'which-player:100:4',
  'which-player:100:29',
];

const ARTIFACT_PATH = path.join(process.cwd(), 'convex', 'seed', 'legacyQuestionKeys.ts');
const SEED_PATH = 'convex/seed/questions.json';

function readSeedAtRef(ref: string): LegacyQuestionKeyRow[] {
  const raw = execFileSync('git', ['show', `${ref}:${SEED_PATH}`], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  return JSON.parse(raw) as LegacyQuestionKeyRow[];
}

function render(corrections: readonly string[], pairs: readonly (readonly [string, string])[]): string {
  const version = createHash('sha256').update(JSON.stringify(pairs)).digest('hex').slice(0, 12);
  const rows = pairs.map((pair) => `  ${JSON.stringify(pair)},`).join('\n');
  const correctionRows = corrections.map((key) => `  ${JSON.stringify(key)},`).join('\n');

  return `/**
 * GENERATED by scripts/build-legacy-question-keys.ts. Do not edit by hand.
 *
 * Frozen snapshot of the question keys the q<UserID> change replaced:
 *   ${SEED_PATH}@${HISTORICAL_REF} (${pairs.length} position-keyed rows)
 *   -> ${SEED_PATH}@${TRANSITION_REF}
 *
 * It is data, not a projection of current content: it is never rebuilt from a later import,
 * so reordering, renaming or adding questions cannot move an old key onto another question.
 * Every pair was verified against prompt and answer identity when it was built.
 */

export const LEGACY_QUESTION_KEY_SOURCE =
  '${SEED_PATH}@${HISTORICAL_REF} (${pairs.length} rows) -> ${SEED_PATH}@${TRANSITION_REF}';

/** sha256 prefix over LEGACY_QUESTION_KEY_PAIRS; a resumed walk must match it. */
export const LEGACY_QUESTION_KEY_VERSION = '${version}';

/** Position keys only ever existed for the English rows. */
export const LEGACY_SEED_LOCALE = 'en';

/** Legacy keys whose prompt/answer the transition deliberately corrected. */
export const LEGACY_CONTENT_CORRECTIONS: readonly string[] = [
${correctionRows}
];

/** [legacyKey, canonicalKey] in historical seed order. */
export const LEGACY_QUESTION_KEY_PAIRS: readonly (readonly [string, string])[] = [
${rows}
];
`;
}

function main() {
  const historical = readSeedAtRef(HISTORICAL_REF);
  const transition = readSeedAtRef(TRANSITION_REF);
  const composition = composeLegacyQuestionKeyPairs(
    historical,
    transition,
    new Set(CONTENT_CORRECTIONS)
  );

  const problems: string[] = [];
  for (const mismatch of composition.mismatches.slice(0, 20)) {
    problems.push(`  ${mismatch.legacyKey} [${mismatch.reason}] ${mismatch.detail}`);
  }
  if (composition.mismatches.length > 20) {
    problems.push(`  ...and ${composition.mismatches.length - 20} more`);
  }
  for (const stale of composition.correctionsStale) {
    problems.push(`  ${stale} [stale-correction] text matches again; remove it from CONTENT_CORRECTIONS`);
  }
  if (problems.length) {
    throw new Error(
      `refusing to write ${path.relative(process.cwd(), ARTIFACT_PATH)}:\n${problems.join('\n')}`
    );
  }

  const uncorrected = CONTENT_CORRECTIONS.filter(
    (key) => !composition.correctionsApplied.includes(key)
  );
  if (uncorrected.length) {
    throw new Error(
      `CONTENT_CORRECTIONS lists unapplied keys: ${uncorrected.join(', ')}`
    );
  }

  fs.writeFileSync(
    ARTIFACT_PATH,
    render(composition.correctionsApplied, composition.pairs),
    'utf8'
  );

  console.log(
    `Wrote ${composition.pairs.length} pairs to ${ARTIFACT_PATH}\n` +
      `  historical ${HISTORICAL_REF}: ${historical.length} rows\n` +
      `  transition ${TRANSITION_REF}: ${transition.length} rows\n` +
      `  corrections applied: ${composition.correctionsApplied.length}, mismatches: 0`
  );
}

main();
